Repository OCA/maintainer-quality-tools, pull requests merged in 2019-03, with the labels that each got.

#587 [REF] pylint-cfg: enable redefined-builtin pylint check
  travis/cfg/travis_run_pylint_beta.cfg
  travis/cfg/travis_run_pylint_exclude_61.cfg
  travis/cfg/travis_run_pylint_exclude_70.cfg
Labels: approved, needs review, ready to merge

#590 [REF] .travis.yml: Enable tests for lints using py3
  .travis.yml
  travis/git_run.py
  travis/self_tests
Labels: approved, needs review

#485 [IMP] Alow excluding specified modules from test_flake8 using env var
  travis/run_pylint.py
  travis/test_flake8
Labels: approved, needs fixing

#592 [FIX] requirements: improve python3 compatibility
  requirements.txt
Labels: approved

#593 [REF] pylint.cfg: Enable print-used instead of print-statement check
  .travis.yml
  tests/test_repo/broken_module/model.py
  travis/cfg/travis_run_pylint.cfg
  travis/self_tests
Labels: needs review

#566 [FIX] Include six in requirements.txt
  requirements.txt
  travis/cfg/travis_run_pylint.cfg
  travis/cfg/travis_run_pylint_beta.cfg
  travis/cfg/travis_run_pylint_exclude_61.cfg
  travis/cfg/travis_run_pylint_exclude_70.cfg
Labels: approved
